<?php

namespace App\Support;

final class ApiErrorCode
{
    public const VALIDATION_ERROR = 'VALIDATION_ERROR';
    public const EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS';
    public const PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS';
    public const USER_NOT_FOUND = 'USER_NOT_FOUND';
    public const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    public const OTP_NOT_VERIFIED = 'OTP_NOT_VERIFIED';
    public const INVALID_OTP = 'INVALID_OTP';
    public const OTP_EXPIRED = 'OTP_EXPIRED';
    public const OTP_ALREADY_VERIFIED = 'OTP_ALREADY_VERIFIED';
    public const OTP_LIMIT_EXCEEDED = 'OTP_LIMIT_EXCEEDED';
    public const PROFILE_ALREADY_COMPLETED = 'PROFILE_ALREADY_COMPLETED';
    public const PROFILE_INCOMPLETE = 'PROFILE_INCOMPLETE';
    public const CLUB_PENDING_APPROVAL = 'CLUB_PENDING_APPROVAL';
    public const CLUB_REJECTED = 'CLUB_REJECTED';
    public const CLUB_NOT_APPROVED = 'CLUB_NOT_APPROVED';
    public const ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED';
    public const RESET_TOKEN_INVALID = 'RESET_TOKEN_INVALID';
    public const RESET_TOKEN_EXPIRED = 'RESET_TOKEN_EXPIRED';
    public const PASSWORD_MISMATCH = 'PASSWORD_MISMATCH';
    public const UNAUTHORIZED = 'UNAUTHORIZED';
    public const FORBIDDEN = 'FORBIDDEN';
    public const SERVER_ERROR = 'SERVER_ERROR';
    public const RECORD_NOT_FOUND = 'RECORD_NOT_FOUND';
    public const DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE';
    public const CLUB_NOT_FOUND = 'CLUB_NOT_FOUND';
    public const COURT_NOT_FOUND = 'COURT_NOT_FOUND';
    public const COURT_NOT_IN_CLUB = 'COURT_NOT_IN_CLUB';
    public const INVALID_DATE = 'INVALID_DATE';
    public const COURT_UNDER_MAINTENANCE = 'COURT_UNDER_MAINTENANCE';
    public const COURT_UNAVAILABLE = 'COURT_UNAVAILABLE';
    public const SLOT_ALREADY_BOOKED = 'SLOT_ALREADY_BOOKED';
    public const CLUB_CLOSED = 'CLUB_CLOSED';
    public const PAYMENT_FAILED = 'PAYMENT_FAILED';
}
